import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Capstone-Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my{" "}
          <a
            href="https://github.com/flohip/capstone-project"
            rel="noreferrer"
            target="_blank"
          >
            Capstone-Project!
          </a>
        </h1>

        <div className={styles.grid}>
          <h2>Documentation &rarr;</h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </div>
      </main>
    </div>
  );
}
