import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import RequestedWord from "../components/RequestedWord/RequestedWord";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Capstone-Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledMain>
        <Header>
          Welcome to my <br />
          <a
            href="https://github.com/flohip/capstone-project"
            rel="noreferrer"
            target="_blank"
          >
            Capstone-Project!
          </a>
        </Header>

        <RequestedWord />
      </StyledMain>
    </>
  );
}

const StyledMain = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const Header = styled.h1`
  color: steelblue;
  background-color: rgb(222, 222, 222);
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
  text-align: center;

  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  > a {
    color: #0070f3;
  }

  > a:hover,
  > a:focus,
  > a:active {
    text-decoration: underline;
  }
`;
